#deployments vem de apps/v1
apiVersion: apps/v1
#tipo
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aplicacao
  template:
    metadata:
      labels:
        app: aplicacao
    spec:
      containers:
        - name: mss-noticias
          image: guisamuka/mss-noticias:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 256Mi

        - name: mss-usuarios
          image: guisamuka/mss-usuarios:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: 256Mi

        - name: barramento
          image: guisamuka/barramento:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10000
          resources:
            limits:
              memory: 256Mi
---
